CREATE TABLE "Diagrams" (
	"GUID"	TEXT NOT NULL,
	"MapName"	TEXT,
	"DraftLevel"	TEXT,
	"MasterLevel"	TEXT,
	"DiagramType"	TEXT,
	"Title"	TEXT,
	"Notation"	TEXT,
	"Author"	TEXT,
	"Owner"	TEXT,
	"DraftVersion"	TEXT,
	"MasterVersion"	TEXT,
	"Date"	TIMESTAMP,
	"DraftAuthorization"	TEXT,
	"MasterAuthorization"	TEXT,
	"DraftTemplate"	TEXT,
	"MasterTemplate"	TEXT,
	"DraftModified"	TIMESTAMP,
	"MasterModified"	TIMESTAMP,
	"DraftUserModified"	TEXT,
	"MasterUserModified"	TEXT,
	"DrillDown"	INTEGER,
	"Description"	TEXT,
	"Status"	TEXT,
	"Organization"	TEXT,
	"URL"	TEXT,
	"Attatchments"	TEXT,
	"PrimaryContact"	TEXT,
	"ParentGUID"	TEXT,
	"Objects"	INTEGER,
	"DraftMapPath"	TEXT,
	"MasterMapPath"	TEXT,
	"DraftDSLID"	TEXT,
	"MasterDSLID"	TEXT,
	PRIMARY KEY("GUID"),
	CONSTRAINT "ParentGUID_CK" FOREIGN KEY("ParentGUID") REFERENCES "Diagrams"("GUID") ON DELETE NO ACTION
);