CREATE TABLE "DiagramLinks" (
	"UUID"	INTEGER UNIQUE,
	"FromGUID"	TEXT,
	"ToGUID"	TEXT,
	"LinkGUID"	TEXT,
	"ActivityID"	TEXT,
	"Type"	TEXT DEFAULT 'Draft',
	"ObjectText"	TEXT,
	"Exists"	INTEGER,
	PRIMARY KEY("UUID" AUTOINCREMENT),
	CONSTRAINT "FromGUID_CK" FOREIGN KEY("FromGUID") REFERENCES "Diagrams"("GUID") ON DELETE CASCADE,
	CONSTRAINT "ToGUID_CK" FOREIGN KEY("ToGUID") REFERENCES "Diagrams"("GUID") ON DELETE CASCADE
);